# nginx proxy address - http://172.17.0.1:5212

name: cloudreve
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  app:
    image: cloudreve/cloudreve:latest
    pull_policy: always
    container_name: cloudreve-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    logging: *default-logging
    networks:
      - cloudreve
    ports:
      - "172.17.0.1:5212:5212"
    environment:
      TZ: ${TZ:-America/New_York}
    volumes:
      - ./volumes/config/cloudreve:/cloudreve/config
      - ./volumes/data/cloudreve:/cloudreve/uploads
      - ./volumes/data/db/sqlite/cloudreve:/cloudreve/db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5212"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  cloudreve:
    name: cloudreve
    external: false
